# Generated by Django 3.1.4 on 2020-12-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('planet', models.CharField(max_length=100)),
                ('solarSystem', models.CharField(max_length=100)),
                ('dateDiscovered', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.IntegerField(max_length=10)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
