# Generated by Django 3.1.4 on 2020-12-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loaction', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='alien',
            name='size',
            field=models.IntegerField(),
        ),
    ]
