# Generated by Django 3.1.4 on 2020-12-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20201205_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='loaction',
            new_name='location',
        ),
    ]
